version: '3.8'

services:
  api:
    image: ghcr.io/Luiso271/examen_aaee_eval3:latest
    container_name: springboot-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://100.26.219.84:3306/hogwarts_lmga
      SPRING_DATASOURCE_USERNAME: examen_lmga
      SPRING_DATASOURCE_PASSWORD: examen
    restart: always
